"""initial_schema_all_tables

Revision ID: 4ee508eaed82
Revises: 
Create Date: 2026-02-06 16:30:45.844208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ee508eaed82'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('admin_telegram_id', sa.BIGINT(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_admin', 'audit_logs', ['admin_telegram_id'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('discounts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('phone', sa.Text(), nullable=False),
    sa.Column('percent', sa.SmallInteger(), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_order_id', sa.UUID(), nullable=True),
    sa.Column('issued_by_admin_telegram_id', sa.BIGINT(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_discounts_is_used', 'discounts', ['is_used'], unique=False)
    op.create_index('ix_discounts_phone', 'discounts', ['phone'], unique=False)
    op.create_index('ix_discounts_valid_until', 'discounts', ['valid_until'], unique=False)
    op.create_index('uq_discounts_one_active_per_phone', 'discounts', ['phone'], unique=True, postgresql_where=sa.text('is_used = false'))
    op.create_table('guests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('phone', sa.Text(), nullable=False),
    sa.Column('telegram_id', sa.BIGINT(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('passport_photo_url', sa.Text(), nullable=True),
    sa.Column('passport_uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trust_flag', sa.Text(), server_default='normal', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('total_orders', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_rebowls', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_guests_telegram_id'), 'guests', ['telegram_id'], unique=False)
    op.create_index('ix_guests_trust_flag', 'guests', ['trust_flag'], unique=False)
    op.create_table('menu_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('item_type', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('price_gel', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_menu_items_type_active_sort', 'menu_items', ['item_type', 'is_active', 'sort_order'], unique=False)
    op.create_table('mixes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('flavors', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('strength', sa.SmallInteger(), server_default='3', nullable=False),
    sa.Column('coolness', sa.SmallInteger(), server_default='3', nullable=False),
    sa.Column('sweetness', sa.SmallInteger(), server_default='3', nullable=False),
    sa.Column('smokiness', sa.SmallInteger(), server_default='3', nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_featured', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('coolness BETWEEN 1 AND 5', name='ck_mixes_coolness'),
    sa.CheckConstraint('smokiness BETWEEN 1 AND 5', name='ck_mixes_smokiness'),
    sa.CheckConstraint('strength BETWEEN 1 AND 5', name='ck_mixes_strength'),
    sa.CheckConstraint('sweetness BETWEEN 1 AND 5', name='ck_mixes_sweetness'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mixes_active_sort', 'mixes', ['is_active', 'sort_order'], unique=False)
    op.create_table('promo_codes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('percent', sa.SmallInteger(), nullable=False),
    sa.Column('max_uses', sa.Integer(), server_default='10', nullable=False),
    sa.Column('used_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by_admin_telegram_id', sa.BIGINT(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_promo_codes_is_active', 'promo_codes', ['is_active'], unique=False)
    op.create_index('ix_promo_codes_valid_until', 'promo_codes', ['valid_until'], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by_admin_telegram_id', sa.BIGINT(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('support_messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('thread_type', sa.Text(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=True),
    sa.Column('telegram_user_id', sa.BIGINT(), nullable=False),
    sa.Column('direction', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_support_messages_is_read', 'support_messages', ['is_read'], unique=False)
    op.create_index('ix_support_messages_telegram_user_id', 'support_messages', ['telegram_user_id'], unique=False)
    op.create_index('ix_support_messages_thread', 'support_messages', ['thread_type', 'thread_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('telegram_id', sa.BIGINT(), nullable=False),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), server_default='ru', nullable=False),
    sa.Column('theme', sa.Text(), server_default='light', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('orders',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('guest_id', sa.UUID(), nullable=True),
    sa.Column('telegram_id', sa.BIGINT(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=False),
    sa.Column('hookah_count', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('status', sa.Text(), server_default='NEW', nullable=False),
    sa.Column('mix_id', sa.UUID(), nullable=False),
    sa.Column('address_text', sa.Text(), nullable=False),
    sa.Column('entrance', sa.Text(), nullable=True),
    sa.Column('floor', sa.Text(), nullable=True),
    sa.Column('apartment', sa.Text(), nullable=True),
    sa.Column('door_code', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('requested_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('promised_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('promised_eta_text', sa.Text(), nullable=True),
    sa.Column('deposit_type', sa.Text(), server_default='cash', nullable=False),
    sa.Column('deposit_amount_gel', sa.Integer(), server_default='100', nullable=False),
    sa.Column('discount_id', sa.UUID(), nullable=True),
    sa.Column('promo_code', sa.Text(), nullable=True),
    sa.Column('promo_percent', sa.SmallInteger(), nullable=True),
    sa.Column('discount_percent', sa.SmallInteger(), nullable=True),
    sa.Column('is_late_order', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('departed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('free_extension_used', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('pickup_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('hookah_count BETWEEN 1 AND 3', name='ck_orders_hookah_count'),
    sa.ForeignKeyConstraint(['discount_id'], ['discounts.id'], ),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ),
    sa.ForeignKeyConstraint(['mix_id'], ['mixes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_orders_created_at', 'orders', ['created_at'], unique=False)
    op.create_index('ix_orders_phone', 'orders', ['phone'], unique=False)
    op.create_index('ix_orders_session_ends_at', 'orders', ['session_ends_at'], unique=False)
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False)
    op.create_index('ix_orders_telegram_id', 'orders', ['telegram_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.Text(), nullable=False),
    sa.Column('mix_id', sa.UUID(), nullable=True),
    sa.Column('menu_item_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('unit_price_gel', sa.Integer(), nullable=False),
    sa.Column('total_price_gel', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.ForeignKeyConstraint(['mix_id'], ['mixes.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_order_items_item_type', 'order_items', ['item_type'], unique=False)
    op.create_index('ix_order_items_order_id', 'order_items', ['order_id'], unique=False)
    op.create_table('promo_code_usages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('promo_code_id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_codes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('promo_code_id', 'phone', name='uq_promo_usage_per_phone')
    )
    op.create_table('rebowl_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('requested_by_telegram_id', sa.BIGINT(), nullable=False),
    sa.Column('mix_id', sa.UUID(), nullable=False),
    sa.Column('price_gel', sa.Integer(), server_default='50', nullable=False),
    sa.Column('add_minutes', sa.Integer(), server_default='120', nullable=False),
    sa.Column('status', sa.Text(), server_default='REQUESTED', nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('in_progress_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['mix_id'], ['mixes.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rebowl_requests_order_id', 'rebowl_requests', ['order_id'], unique=False)
    op.create_index('ix_rebowl_requests_status', 'rebowl_requests', ['status'], unique=False)
    op.create_index('uq_rebowl_one_active_per_order', 'rebowl_requests', ['order_id'], unique=True, postgresql_where=sa.text("status IN ('REQUESTED', 'IN_PROGRESS')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_rebowl_one_active_per_order', table_name='rebowl_requests', postgresql_where=sa.text("status IN ('REQUESTED', 'IN_PROGRESS')"))
    op.drop_index('ix_rebowl_requests_status', table_name='rebowl_requests')
    op.drop_index('ix_rebowl_requests_order_id', table_name='rebowl_requests')
    op.drop_table('rebowl_requests')
    op.drop_table('promo_code_usages')
    op.drop_index('ix_order_items_order_id', table_name='order_items')
    op.drop_index('ix_order_items_item_type', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('ix_orders_telegram_id', table_name='orders')
    op.drop_index('ix_orders_status', table_name='orders')
    op.drop_index('ix_orders_session_ends_at', table_name='orders')
    op.drop_index('ix_orders_phone', table_name='orders')
    op.drop_index('ix_orders_created_at', table_name='orders')
    op.drop_table('orders')
    op.drop_table('users')
    op.drop_index('ix_support_messages_thread', table_name='support_messages')
    op.drop_index('ix_support_messages_telegram_user_id', table_name='support_messages')
    op.drop_index('ix_support_messages_is_read', table_name='support_messages')
    op.drop_table('support_messages')
    op.drop_table('settings')
    op.drop_index('ix_promo_codes_valid_until', table_name='promo_codes')
    op.drop_index('ix_promo_codes_is_active', table_name='promo_codes')
    op.drop_table('promo_codes')
    op.drop_index('ix_mixes_active_sort', table_name='mixes')
    op.drop_table('mixes')
    op.drop_index('ix_menu_items_type_active_sort', table_name='menu_items')
    op.drop_table('menu_items')
    op.drop_index('ix_guests_trust_flag', table_name='guests')
    op.drop_index(op.f('ix_guests_telegram_id'), table_name='guests')
    op.drop_table('guests')
    op.drop_index('uq_discounts_one_active_per_phone', table_name='discounts', postgresql_where=sa.text('is_used = false'))
    op.drop_index('ix_discounts_valid_until', table_name='discounts')
    op.drop_index('ix_discounts_phone', table_name='discounts')
    op.drop_index('ix_discounts_is_used', table_name='discounts')
    op.drop_table('discounts')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_admin', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
